### ISSUE TITLE
Add xText project into the repository

### ISSUE THREAD

**Issue by IgorNikiforov** [AnastasiaShemyakinskaya/Application-configurator#1]
There is a need to have 2 projects inside the repository:
 - xText project (Package name: ru.spbstu.application.configurator.model)
 - RCP application project, which depends on xtext project - Package name:  ru.spbstu.application.configurator.ui

**Comment by AnastasiaShemyakinskaya** [comment]
Проект добавлен, имена пакетов также изменены в соответствии с требованиями.
