### ISSUE TITLE
Build RCP application for the end user

### ISSUE THREAD

**Issue by IgorNikiforov** [AnastasiaShemyakinskaya/Application-configurator#9]
There is a need to have build for our RCP-application, which generate a distribution to the end user.
Distribution should contain:
 - executable file
 - folder with libs (jars)
 - folder with configuration

**Comment by AnastasiaShemyakinskaya** [comment]
https://drive.google.com/drive/u/1/folders/1ct2Ozx35274N8xkYtPGCSAJlxwrazwMp
